#!/bin/sh

set -e

CMD="bundle exec unicorn -c config/unicorn.rb -E production -D"
export PID=tmp/pids/unicorn.pid
export OLD_PID="$PID.oldbin"

haz_proc () {
  if [ -s "$1" ]; then
    ps `cat $1` 2>&1 >/dev/null
  else
    return 1
  fi
}

start () {
  if haz_proc "$PID"; then
    echo "Already Running"
    exit 0
  fi

  echo "Starting"
  $CMD
}

stop () {
  if haz_proc "$PID"; then
    echo "Stopping Process"
    kill -QUIT `cat $PID`
  else
    echo "Not Running"
  fi
}

restart () {
  if haz_proc "$PID"; then
    echo "Triggering Restart"
    kill -USR2 `cat $PID`
    sleep 15
    if haz_proc "$OLD_PID"; then
      echo "Restart in progress"
      exit 0
    else
      echo >&2 "Failed to restart, performing hard stop/start"
      stop
      sleep 5
      start
    fi
  else
    start
  fi
}

case $1 in
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  *) echo >&2 "Usage: $0 <start|stop|restart>" && exit 1 ;;
esac

